- hosts: testhost
  tasks:
    - name: Updates apt cache
      apt: update_cache=true

    - name: Installs necessary packages
      apt: pkg={{ item }} state=latest
      with_items:
        - python3
        - git

    - name: Install and upgrade pip
      pip:
        name: pip
        extra_args: --upgrade
        executable: pip3

    - name: Deploy our awesome application
      git: repo=https://github.com/anfederico/flaskex.git dest=/Flaskex
      tags: deploy

    - name: Install specified python requirements
      pip:
        requirements: /Flaskex/requirements.txt
    
    - name: run Flaskex
      command: python3 /Flaskex/app.py
      async: True
      poll: 0
